title: Chaofa Zhao's Homepage
page-top-title: Chaofa Zhao
top-section-bg-text: College of Civil Engineering and Architecture, Zhejiang University
home-subtitle: Chaofa Zhao&ensp;|&ensp;赵朝发
copyright-text: '&copy; Chaofa Zhao 2023-2024. All Rights Reserved.'
